### ISSUE TITLE
CalDAV is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#146]
## The problem

The CalDAV integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/caldav/icon.png`
- `src/caldav/logo.png`
- `src/caldav/icon@2x.png`
- `src/caldav/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

**Comment by sim-san** [comment]
@frenck I believe this is the general brand image for all DAV protocols.

![grafik](https://user-images.githubusercontent.com/7436938/154451136-ec7d8362-1742-4b1a-ba55-ca407ed1b310.png)

http://webdav.org/images/webdav-logo.jpg
