### ISSUE TITLE
Custom integrations not available at placeholder url

### ISSUE THREAD

**Issue by RogerSelwyn** [home-assistant/brands#1585]
## The problem

Custom integration images don't seem to be made available at the placeholder url, so the default not available image is presented.

Skyq is available here:
`https://brands.home-assistant.io/skyq/icon.png`

But not here
`https://brands.home-assistant.io/_/skyq/icon.png`

Whilst core integrations are available at both locations.

**Comment by frenck** [comment]
The logo has been recently added. Requests are cached, you'll have to wait until the cache expires or we do a release of Home Assistant.

**Comment by RogerSelwyn** [comment]
Thanks
