### ISSUE TITLE
Icon not displayed for unifiprotect

### ISSUE THREAD

**Issue by briis** [home-assistant/brands#1617]
## The problem
I have submitted both icon and logo files for the custom component unifiprotect. All 4 files are merged and I can see them in the directory. But when adding the Integration, the Icon is not shown on list of Integrations. However when the Integration has been added, the Logo is displayed fine. When accessing https://brands.home-assistant.io/unifiprotect/icon.png (or icon2x) the icon shows fine.

## Additional information
Testet on both 0.109.6,  0.110 and 0.111 dev branches

**Comment by frenck** [comment]
It can take a while for the cache of the CDN endpoints expire. We also flush our cache on release of Home Assistant Core.

So it can take up to 3 weeks (as HA has a 3 week release cycle) for they show up.

**Comment by briis** [comment]
Good to know, thanks.
