### ISSUE TITLE
Logitech Harmony logo invisible on dark or black themes

### ISSUE THREAD

**Issue by rpitera** [home-assistant/brands#1618]
## The problem

The Logitech Harmony brand logo is black on a transparent background.  This renders it invisible on themes using black backgrounds and near invisible on dark background themes.
## Additional information
Suggest a logo colored in traditional HA blue instead which should work on most themes.  Example included.

![logitechlogo](https://user-images.githubusercontent.com/19910294/82065057-98731e80-969b-11ea-9af0-ea4097e25292.png)

**Comment by frenck** [comment]
We don't change colors of logos or icons because of a theme. The images in this repository respect the design by the brand.

**Comment by rpitera** [comment]
> We don't change colors of logos or icons because of a theme. The images in this repository respect the design by the brand.

Understood and that's not exactly what I am asking. The official authorized Logitech logo is available from their brand assets page in both black and white coloring as well as black on a white background.  See examples here:

https://www.logitech.com/en-us/pr/library

Perhaps the black lettering on a white background would be a suitable choice than a transparent one?
