### ISSUE TITLE
Improved graphics for deCONZ

### ISSUE THREAD

**Issue by Kane610** [home-assistant/brands#1634]
## Additional information
deCONZ guys have been nice enough to share better graphics to be used here, it can be found: https://phoscon.de/downloads/Phoscon_Iconset.zip

**Comment by BradleyFord** [comment]
Kane610 is there a problem with the existing graphics?

**Comment by djpremier** [comment]
@frenck I checked the zip and the logos are the same, but with lower resolution than the existing ones. In my opinion, this issue can be closed.
