### ISSUE TITLE
eBusd is missing brand logo

### ISSUE THREAD

**Issue by ausserirdischesindgesund** [home-assistant/brands#1636]
## The problem

There is no logo for the ebusd/eBUS integration, I've thereforme resized and edited the eBUS logo from German Wikipedia.
 

## Additional information

I am not sure if this is acceptable: ebusd does not seem to have a logo, but the bus it attaches to has (eBUS), I picked it from Wikipedia. I hope this is acceptable. eBUS interest group seems to have fallen off the net, but the logo is still there.

Integration:
https://www.home-assistant.io/integrations/ebusd/

Logo Source:
https://de.wikipedia.org/wiki/EBus#/media/Datei:EBus_Logo.png

Thanks for considering!

![icon_256x256](https://user-images.githubusercontent.com/20264332/82435311-67785c80-9a94-11ea-9496-918ac6c98a60.png)
![icon_512x512](https://user-images.githubusercontent.com/20264332/82435339-73641e80-9a94-11ea-9328-30a1e27000b7.png)
![ebus_logo_large](https://user-images.githubusercontent.com/20264332/82435358-7959ff80-9a94-11ea-815c-6225d40cf174.png)

**Comment by tikismoke** [comment]
For my opinion the "mulit" part is not needed.
eBus is often write with a small 'e' and capital BUS like those it's really nice to see like you've found.
