### ISSUE TITLE
Meross Cloud custom integration logo not found

### ISSUE THREAD

**Issue by pablitofernandez** [home-assistant/brands#1659]
Hello, last week I pulled a request to add Meross Cloud logos succesfully (https://github.com/home-assistant/brands/pull/1639).

The problem is "https://brands.home-assistant.io/meross_cloud/logo.png" is not working. Other 3 versions of logo/icon are indeed working but not "logo.png".

Thanks!

**Comment by frenck** [comment]
This is due to caching. Our CDN and caches are flushed on major Home Assistant releases. It can take up to the release of Home Assistant 0.111 before it becomes visible.

**Comment by pablitofernandez** [comment]
Ah ok! Thanks for the clarification.
