### ISSUE TITLE
Daikin AC is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#174]
## The problem

The Daikin AC integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/daikin/icon.png`
- `src/daikin/logo.png`
- `src/daikin/icon@2x.png`
- `src/daikin/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).
## Updating the documentation repository

Our documentation repository already has a logo for this integration, however, it does not meet the image requirements of this new Brands repository.

If adding images to this repository, please open up a PR to the documentation repository as well, removing the `logo: daikin.png` line from this file:

<https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/daikin.markdown>

**Note**: The documentation PR needs to be opened against the `current` branch.
**Note2**: Please leave the actual logo file in the documentation repository. It will be cleaned up differently.

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @fredrike, @rofrantz! Mind taking a look at this issue as it is with an integration (daikin) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/daikin/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by fredrike** [comment]
The logo can be found here: https://worldvectorlogo.com/logo/daikin I'll try to convert the SVG to png..

**Comment by fredrike** [comment]
Will we have support for SVG images?

**Comment by frenck** [comment]
No, we won't be adding support for SVG right now.

**Comment by fredrike** [comment]
> No, we won't be adding support for SVG right now.

That is too bad as that would support variable sizes..
