### ISSUE TITLE
Logo file not served of [plugwise_stick] domain

### ISSUE THREAD

**Issue by brefra** [home-assistant/brands#1773]
## The problem

The logo file is not served at https://brands.home-assistant.io/plugwise_stick/logo.png while the icon file is available at https://brands.home-assistant.io/plugwise_stick/icon.png

Already tried clearing cache of browser without result.

## Additional information
Both source image are part of the `plugwise_stick` custom_integrations and listed in source [overhere](https://github.com/home-assistant/brands/tree/master/custom_integrations/plugwise_stick)

Image files where recently add by PR #1765

**Comment by frenck** [comment]
We use pretty hard caching on our websites, which will be flushed on the next release of Home Assistant.
