### ISSUE TITLE
Cannot get the logo to show

### ISSUE THREAD

**Issue by jm-73** [home-assistant/brands#1783]
## The problem
I have done a PR #1772 for the folder "indego" to be created with a symlink to the folder "bosch". The PR has been accepted. But i cant reach the logos that I want to access. The links:

https://raw.githubusercontent.com/home-assistant/brands/master/custom_integrations/bosch/icon.png
and
https://raw.githubusercontent.com/home-assistant/brands/master/custom_integrations/indego/icon.png
(404 not found)

Shouldn't they show the same logo? Is there something wrong with the symlink in my PR for the indego folder?

-->

## Additional information

**Comment by jm-73** [comment]
My manifest.json domain:
```
  "domain": "indego",
```

**Comment by frenck** [comment]
The cache is flushed on Home Assistant release. So it can take up to 3 weeks before the icons show after merge.
