### ISSUE TITLE
Denon AVR Network Receivers is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#185]
## The problem

The Denon AVR Network Receivers integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/denonavr/icon.png`
- `src/denonavr/logo.png`
- `src/denonavr/icon@2x.png`
- `src/denonavr/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).
## Updating the documentation repository

Our documentation repository already has a logo for this integration, however, it does not meet the image requirements of this new Brands repository.

If adding images to this repository, please open up a PR to the documentation repository as well, removing the `logo: denon.png` line from this file:

<https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/denonavr.markdown>

**Note**: The documentation PR needs to be opened against the `current` branch.
**Note2**: Please leave the actual logo file in the documentation repository. It will be cleaned up differently.

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @scarface-4711, @starkillerOG! Mind taking a look at this issue as it is with an integration (denonavr) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/denonavr/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by starkillerOG** [comment]
@scarface-4711 I found the picture below on google, do you think that is okay as a logo?
I like it mentioning both Denon and Marantz sinds both brands are covered by this same integration.

![denon_marantz_logo](https://user-images.githubusercontent.com/14811189/78503970-61d7e900-776a-11ea-83e2-caf0c3eff710.jpg)

The current logo used now looks like this:
![current-denon-logo](https://user-images.githubusercontent.com/14811189/78504050-d579f600-776a-11ea-9184-97e50d357f0a.png)
