### ISSUE TITLE
Seccasa_simulator logo.png not working

### ISSUE THREAD

**Issue by u8915055** [home-assistant/brands#1867]
## The problem

I just recently issued a PR for the icons and logos for a custom integration called seccasa_simulator.  I see that it has been committed and it seems though that only 3 out of the 4 graphic files work.  The logo.png yields a page-not-found error when I try to retrieve it, but logo@2x, icon, and icon@2x work fine.  Can someone take a look at this?

**Comment by frenck** [comment]
It can take up to 3 weeks before it is visible, due to heavy caching.
