### ISSUE TITLE
Handling "generic" items

### ISSUE THREAD

**Issue by mrand** [home-assistant/brands#1902]
## The problem

Short version: There are a number of integrations which aren't tied to one company and/or don't have a recognizable logo.

Rather than throwing ideas into bunch of different issues, I'm thinking it might be better to take a more high level view.
I saw a few of the open items and am realizing that there isn't much consistency in how the "branding" is handled.  Course, maybe I'm being too rigid about it (if so, just say so)!

Is that ok to use pictures of a physical device for the logo, or is the intent to avoid pictures? It would be nice if the outcome of this discussion is captured as guidance [at the top level](https://github.com/home-assistant/brands/) about which of the following are preferred, acceptable, and not-acceptable.

### I2C sensors

For example, the Sensirion SHT31 uses its [brand logo](https://github.com/home-assistant/brands/pull/1454) while the Time of Flight sensor (which as far as I can tell, has no Pi hat, so it's as generic as any other I2C sensor) currently uses a Raspberry Pi logo.

I suppose Pi logo was chosen because it's currently the most common way that someone is using an I2C device. But they could be connecting it to an Beagle Bone, Orange Pi, or some other single-board-computer - so it seems strange to just blindly lump anything I2C under the Pi logo.  At a minimum, it dilutes the usefulness of logo, if not bordering on misleading.

Choices that I see:

0. Don't worry about consistency.  Decide what works for each device on case-by-case basis 
1. Use picture of the device.  Example: [ToF picture](https://www.st.com/en/imaging-and-photonics-solutions/vl53l1x.html)
2. Try to find (or have someone create) semi-custom graphic logos for each.  Example: [ToF graphic](https://www.fujitsu.com/uk/Images/tof_principle_tcm23-2692940.png) and [GPIO graphic](https://user-images.githubusercontent.com/435987/94947234-eb127300-04a2-11eb-97ac-9435b80a45db.png)
3. Use Pi logo
4. Don't use a logo and just let the HA text indicate the sensor
5. use I2C bus logo (similar to what the 1-wire sensor does):
![image](https://user-images.githubusercontent.com/435987/94961291-fae98180-04b9-11eb-8a71-4bc5ebb0eef3.png)

.... or other ideas?

### Serial-port sensors

I assume that these sensors would follow the same guidance as above.  Example: Serial particulate matter sensor [integration page](https://www.home-assistant.io/integrations/serial_pm/) has a picture of a sensor.  If option #5 above is acceptable, here is an example generic serial port logo that could get re-used across integrations:
![image](https://user-images.githubusercontent.com/435987/94961886-2de04500-04bb-11eb-9ce9-9e642644c25e.png)

Presumably [MH-Z19 CO2 sensor](https://www.home-assistant.io/integrations/mhz19/) and any others would be done the same way, whatever is agreed upon.

### other generic sensors

I haven't gone looking, but to round out the discussion, it wouldn't surprise me if there are other DIY or generic (ali-express) sensors that don't have meaningful logos - maybe some that connect via Ethernet or SPI or simply GPIO toggling.  

And then we have things that simply don't have logo's... SNMP, among many other examples.

**Comment by Shulyaka** [comment]
+1. Some integrations are better described by its functionality rather by its brand name.

**Comment by frenck** [comment]
I'm not sure if this is a question or an issue? I kinda fail to see the problem at all.
Have those images been rejected in PRs? Is there a description in our repository readme that forbids the use of this?

I'm confused by the goal of this issue.

**Comment by Shulyaka** [comment]
This is a question. We have a couple of issues like #528 and we need an advice on how to proceed with them. An official policy or description on how to handle such cases would be very helpful.

**Comment by frenck** [comment]
There isn't an official policy for either of those. We have many integration with generic images already. None have been rejected.
