### ISSUE TITLE
Only 3 of the Easee custom integration brand files are actually on the web server

### ISSUE THREAD

**Issue by olalid** [home-assistant/brands#1942]
## The problem
From the logo files for custom component easee, only 3 of the 4 files in the brands git repository is actually available on the web server.
https://brands.home-assistant.io/easee/logo.png : NOT available
https://brands.home-assistant.io/easee/logo@2x.png : available
https://brands.home-assistant.io/easee/icon.png : available
https://brands.home-assistant.io/easee/icon@2x.png : available

**Comment by frenck** [comment]
This is correct. That PR was merged 5 days ago. The cache will be force flushed on each major HA release.
