### ISSUE TITLE
Perfectionist-unfriendly logos for core integrations (perfectionists, you've been warned)

### ISSUE THREAD

**Issue by Shulyaka** [home-assistant/brands#2000]
## The problem

Most of the logos for base core integrations contain some kind of shadow spot at the left side just under the roof.
If there was any automated process was involved to overlay an icon over the house background, then could they be regenerated?

## Additional information
![изображение](https://user-images.githubusercontent.com/2741408/97981260-0b578980-1de3-11eb-8009-7a909ed389ec.png)
![изображение](https://user-images.githubusercontent.com/2741408/97981343-304bfc80-1de3-11eb-8b6c-e9b1a9a4ed42.png)
Now you also know it and will never unsee. Sorry for that.

**Comment by frenck** [comment]
Feel free to contribute a fix.
