### ISSUE TITLE
Simple Icons Already Exists

### ISSUE THREAD

**Issue by IIAIronWolf** [home-assistant/brands#2025]
## The problem
There is already a website like MDI called Simple Icons that contains tons of brand images. Why add our own repository when we could integrate Simple Icons like we have MDI Icons?
When MDI was updated to 5.x.x, brand icons were removed. MDI themselves suggest using Simple Icons. 

## Additional information
https://simpleicons.org/

**Comment by frenck** [comment]
I'm confused, what does simpleicons have to do with collecting brand images?

**Comment by IIAIronWolf** [comment]
I’m now also confused..Simple Icons IS brand images. It is the brand images version of MDI. So why waste resources collecting brand images when it has already been done? We don’t collect MDI-type icons because MDI already offers them. Why collect our own brand images when Simple Icons already offers them?

**Comment by frenck** [comment]
e.g., <https://brands.home-assistant.io/hue/logo.png>

Is not a font/icon/vector thingy that Simple icons tries to be. Furthermore, most brands we have are not in that repository either.

Project goals are not related.

**Comment by IIAIronWolf** [comment]
K.
