### ISSUE TITLE
Logo doesn't seem to work

### ISSUE THREAD

**Issue by filipvh** [home-assistant/brands#2037]
## The problem
A custom component called 'nhc2' was added, but it seems to not get live?
https://brands.home-assistant.io/nhc2/logo.png
the url https://brands.home-assistant.io/_/nhc2/logo.png
seems to work... but the icon is also missing...
Did I understand incorrectly how this all works, or is there an issue?

## Additional information
https://github.com/home-assistant/brands/tree/master/custom_integrations/nhc2

**Comment by frenck** [comment]
You'll have to wait until the next Home Assistant release until the caches are flushed.
