### ISSUE TITLE
Logo for Ngenic getting 404 Not Found

### ISSUE THREAD

**Issue by sfalkman** [home-assistant/brands#2057]
## The problem

I'm getting a 404 Not Found for the Ngenic `logo.png`, while the others are working fine.

## Additional information
```
curl -I https://brands.home-assistant.io/ngenic/logo.png -H 'Cache-Control: no-cache'
HTTP/2 404

curl -I https://brands.home-assistant.io/ngenic/logo@2x.png -H 'Cache-Control: no-cache'
HTTP/2 200

curl -I https://brands.home-assistant.io/ngenic/icon.png -H 'Cache-Control: no-cache'
HTTP/2 200

curl -I https://brands.home-assistant.io/ngenic/icon@2x.png -H 'Cache-Control: no-cache'
HTTP/2 200
```

**Comment by frenck** [comment]
These images have been added 10 hours ago... It can take up to 3 weeks before they are available (on Home Assistant release). It may be sooner, but a release is a guaranteed cache flush.
