### ISSUE TITLE
emporia_vue missing brand ico/image

### ISSUE THREAD

**Issue by radiumfu** [home-assistant/brands#2112]
I believe these are good image to present this integration
![image](https://user-images.githubusercontent.com/15271818/103240420-2f2bdd00-4905-11eb-8bb0-cd15ea46413f.png)

![image](https://user-images.githubusercontent.com/15271818/103240449-3eab2600-4905-11eb-8055-31f0c76c923e.png)

https://github.com/Magico13-Org/ha-emporia-vue

**Comment by frenck** [comment]
That is a custom integration and not managed by Home Assistant. We are happy to add it, but the original owner of that custom integration needs to open a PR to add it. Maybe open an issue with the upstream integration to request that?

Nevertheless, thanks for the suggestion! Happy Holidays!
