### ISSUE TITLE
no_ip has no images

### ISSUE THREAD

**Issue by Misiu** [home-assistant/brands#2630]
## The problem

the no_ip integration (https://www.home-assistant.io/integrations/no_ip/) has no images:
![image](https://user-images.githubusercontent.com/1741838/121492483-363c3880-c9d7-11eb-94b0-dfa1a173660d.png)

Integration is called `no_ip`, but the folder containing the images is called `noip` (https://github.com/home-assistant/brands/tree/master/core_integrations/noip)
## Additional information
Should we rename the folder?

**Comment by frenck** [comment]
> Should we rename the folder?

Yes

**Comment by Misiu** [comment]
@frenck I've created PR with the rename.
