### ISSUE TITLE
FortiGate is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#271]
## The problem

The FortiGate integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/fortigate/logo.png`
- `src/fortigate/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @kifeo! Mind taking a look at this issue as it is with an integration (fortigate) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/fortigate/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by kifeo** [comment]
Hi @frenk, I will abandon this fortigate integration, in order to only have the fortios one, which I will update when I have time.

**Comment by frenck** [comment]
Thanks for letting me know @kifeo! Let's close up this issue in that case. 👍
