### ISSUE TITLE
Cache not updated.

### ISSUE THREAD

**Issue by Wh1terat** [home-assistant/brands#2790]
Placeholder image is still being displayed some ~5 hours after merge.

https://brands.home-assistant.io/cleverspa/icon.png 
Results in 404.

https://brands.home-assistant.io/cleverspa/icon.png?foo=123
Results in logo.

Looks like a cache issue?

**Comment by ludeeus** [comment]
The cache is flushed after each core release which happens on the first Wednesday each month.

**Comment by Wh1terat** [comment]
I checked 3 or 4 other merge requests that you accepted at the same time as mine and they seemingly work?

The main page also states:

Caching
All icons are cached on the client-side browser end for 900 seconds, and cached by Cloudflare for 604800 seconds.

Placeholder images are excepted from this. Placeholder images have a 900 seconds cache on the client-side and are cached for 1 hour on Cloudflare. This allows us to replace placeholder images within an acceptable time frame without losing our cache.

**Comment by ludeeus** [comment]
They work because no one has visited them, causing the 404 page to be cached in it's place.

**Comment by Wh1terat** [comment]
Sounds a little surprising given I imagine the developers of those plugins would have likely pulled the image in within their dev environment?

Also the main brands page does state that placeholder images are exempt and should update within 60 minutes, guessing with cloudflare cache rules.

Doesn't sound like that's fully working?

**Comment by ludeeus** [comment]
<https://brands.home-assistant.io/_/cleverspa/icon.png> is the placeholder URL, which has the cache lifted and it's now showing your image

**Comment by Wh1terat** [comment]
```shell
gareth@GB-MacBook:[/tmp]$ wget -v https://brands.home-assistant.io/cleverspa/icon.png
--2021-09-03 18:41:17--  https://brands.home-assistant.io/cleverspa/icon.png
Resolving brands.home-assistant.io (brands.home-assistant.io)... 104.26.5.238, 172.67.68.90, 104.26.4.238, ...
Connecting to brands.home-assistant.io (brands.home-assistant.io)|104.26.5.238|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-03 18:41:18 ERROR 404: Not Found.

gareth@GB-MacBook:[/tmp]$ wget -v https://brands.home-assistant.io/_/cleverspa/icon.png
--2021-09-03 18:41:25--  https://brands.home-assistant.io/_/cleverspa/icon.png
Resolving brands.home-assistant.io (brands.home-assistant.io)... 172.67.68.90, 104.26.5.238, 104.26.4.238, ...
Connecting to brands.home-assistant.io (brands.home-assistant.io)|172.67.68.90|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /_/_placeholder/icon.png [following]
--2021-09-03 18:41:25--  https://brands.home-assistant.io/_/_placeholder/icon.png
```
