### ISSUE TITLE
Icon link is broken/not found windcentrale

### ISSUE THREAD

**Issue by jobvk** [home-assistant/brands#2797]
## Problem
Image [link](https://brands.home-assistant.io/windcentrale/icon.png) not found for icon?
The link is broken or not found.
![image](https://user-images.githubusercontent.com/32730202/132136764-7e968fa5-ca25-4e5a-bf5d-c61e37ee9ebf.png)
![image](https://user-images.githubusercontent.com/32730202/132136767-7eaf3583-04d4-4fae-bd3b-6df5440bb03f.png)
![image](https://user-images.githubusercontent.com/32730202/132136878-c95b8aca-4358-416d-92d2-1f6f613b40c9.png)

After recently added the icon and logo #2784 
I waited a  time for the cache to be refreshed but still the link is broken?

## Additional information
All other images work perfectly and also show up.

- [icon@2x](https://brands.home-assistant.io/windcentrale/icon@2x.png)
- [logo](https://brands.home-assistant.io/windcentrale/logo.png)
- [logo@2x](https://brands.home-assistant.io/windcentrale/logo@2x.png)

Example of the logo working perfect
![image](https://user-images.githubusercontent.com/32730202/132136927-d5e04baf-6407-42cf-a812-8ae47e679b9c.png)

**Comment by ludeeus** [comment]
It's just cached, cache is flushed after each main release.
