### ISSUE TITLE
Integration using logos from other brands/integrations

### ISSUE THREAD

**Issue by Rjevski** [home-assistant/brands#2968]
I've recently been working on improving an integration for a [third-party gateway that can talk to multiple different brands of HVAC devices](https://www.home-assistant.io/integrations/coolmaster/) and I was wondering whether it would be possible to use the brand-specific logo on the climate devices?

At the moment I am able to detect which brand each unit is and set it properly in the device info (as you can see below it says "by Mitsubishi Electric"). Is there a way to do the same for the "CoolAutomation" logo which currently seems to be magically looked up based on the integration's domain (I didn't see an explicit variable to set which brand it uses)?

<img width="827" alt="image" src="https://user-images.githubusercontent.com/45625150/143670704-bb99f025-3aff-4460-ad4a-7c1fed60b53d.png">

**Comment by frenck** [comment]
No, it cannot, it is tied to the integration domain registering the device & entities.
