### ISSUE TITLE
Google Translate Text-to-Speech is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#301]
## The problem

The Google Translate Text-to-Speech integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/google_translate/logo.png`
- `src/google_translate/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @awarecan! Mind taking a look at this issue as it is with an integration (google_translate) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/google_translate/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by adrianmihalko** [comment]
There is no logo for Google Translate Text-to-Speech and available icons are high quality icons. I suggest you to close this issue.

**Comment by frenck** [comment]
✅ 👍
