### ISSUE TITLE
speedtestdotnet does not serve dark icon

### ISSUE THREAD

**Issue by kongo09** [home-assistant/brands#3075]
## The problem

The repository shows a proper `dark_icon.png` for the `speedtestdotnet` core integration. However, in my browser I only resolve the normal light theme png:

https://brands.home-assistant.io/speedtestdotnet/dark_icon.png

![image](https://user-images.githubusercontent.com/640121/148510040-7fad471a-81f1-41dc-97b5-cd7dca968a08.png)

**Comment by frenck** [comment]
Those have been merged 2 days ago. You are looking at cache.

Cache is fully flushed on each Home Assistant Core major release.

**Comment by kongo09** [comment]
Thanks, understood.
