### ISSUE TITLE
rinnaitouch icon and logo results in 404

### ISSUE THREAD

**Issue by funtastix** [home-assistant/brands#3274]
## The problem

After [adding](https://github.com/home-assistant/brands/commit/ba3d7177b2310c660509d341ec461102f7fca209) the rinnaitouch logo and icon, some result in a 404. Some versions seem to appear correctly though:

https://brands.home-assistant.io/rinnaitouch/logo.png -> 404
https://brands.home-assistant.io/rinnaitouch/dark_logo.png -> 200
https://brands.home-assistant.io/rinnaitouch/icon.png -> 404
https://brands.home-assistant.io/rinnaitouch/dark_icon.png -> 404
https://brands.home-assistant.io/rinnaitouch/icon@2x.png -> 200
https://brands.home-assistant.io/rinnaitouch/dark_icon@2x.png -> 200
https://brands.home-assistant.io/rinnaitouch/logo@2x.png -> 200
https://brands.home-assistant.io/rinnaitouch/dark_logo@2x.png -> 200

**Comment by frenck** [comment]
That is caused by the caching we apply. Our change is flushed each major Home Assistant release.
