### ISSUE TITLE
Bayesian icon 

### ISSUE THREAD

**Issue by dgomes** [home-assistant/brands#3399]
## The problem

The Bayesian icon is a Gaussian distribution

I purpose the use of mdi:graph since it shares similarities with diagrams usually used when analysing bayesian networks (I'm not claiming the sensor implements a bayes network!)
One thing is for sure, a Gaussian distribution has nothing to do with bayesian sensor.

## Additional information
This can be a little pedantic of my own, so I opened an issue instead of a PR for discussion

**Comment by frenck** [comment]
Feel free to open up a PR, I have no opinion on it myself 🤷
