### ISSUE TITLE
custom integration icons not found

### ISSUE THREAD

**Issue by BottlecapDave** [home-assistant/brands#3488]
## The problem

I have recently had a PR approved and merged (https://github.com/home-assistant/brands/pull/3472/files), however it doesn't seem to be available via the brands domain (e.g. https://brands.home-assistant.io/octopus_energy/icon.png). I'm not sure if I submitted something wrong?

**Comment by KTibow** [comment]
It works fine now. Consider closing?

**Comment by klaasnicolaas** [comment]
It takes some time before a logo/icon is visible because we only empty the cache after a release 😉
