### ISSUE TITLE
Missing ODROID-C2 picture hardkernel_odroid-c2.png

### ISSUE THREAD

**Issue by ARGO1960** [home-assistant/brands#3636]
## Additional information
The SYSTEM->HARDWARE pages end up with a missing picture:
https://brands.home-assistant.io/hardware/boards/hardkernel_odroid-c2.png
hereby one.
![hardkernel_odroid-c2](https://user-images.githubusercontent.com/14184860/188077784-333ce227-1a88-4a77-9ead-636ad8977200.png)

**Comment by frenck** [comment]
Issues was fixed (as reported in #3987)
