### ISSUE TITLE
Custom integration icon recently added shows Page Not Found error

### ISSUE THREAD

**Issue by nirnachmani** [home-assistant/brands#3704]
## The problem
I recently merged icons and logo for pixie_plus into brands. I can see that the files are in the correct directory. When trying to access the icon and logo through the link "https://brands.home-assistant.io/pixie_plus/icon.png" and "https://brands.home-assistant.io/pixie_plus/logo.png" I receive "Page Not Found" error. Link for the hDPI  icon "https://brands.home-assistant.io/pixie_plus/icon@2x.png" works fine. When using placeholder links none of the icons and logo work

**Comment by klaasnicolaas** [comment]
logos are not immediately visible after merging, only when we flush the cache during a major release. I think your logos are now visible, at least I can access them at.

**Comment by nirnachmani** [comment]
Thank you. I'll wait. I still get "Page Not Found" for all but the hDPI icon, even after clearing my cache.

**Comment by nirnachmani** [comment]
Strange - links still not working but icons shows in HA.
