### ISSUE TITLE
Solax integration hangs dashboard if it cannot connect

### ISSUE THREAD

**Issue by jefft4** [home-assistant/brands#4009]
## The problem
I have the Solax integration set up in HA, part of testing HA.  The reverse proxy that I use to connect to the inverter's WLAN was down when I restarted HA today.  The result of this was that the HA dashboard/'overview' page said it was loading and displayed no widgets at all.  A pop-up notification then told me that the Solax integration was loading and that 'not everything' would be available until it completed.
After several minutes of this situation, I decided to disable the integration (the proxy needs to wait for delivery of a new wi-fi dongle); this caused HA to tell me that a reboot would be required.  Still nothing on the overview page.  After a reboot, the dashboard was displayed properly, without the Solax entities.

The issue here, is that a problem in one integration made the HA system unusable. That should not happen; integrations/connectors/add-ins should be isolated sufficiently that their problems don't affect other parts of the system.

I don't know whether this is an issue with how the Solax integration is built, or with HA's integration architecture, so I've raised it as an brand integration problem initially.  Please move it to core if it's really a core issue.

## Additional information
HAOS; virtual machine.
Home Assistant 2022.12.9
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

**Comment by klaasnicolaas** [comment]
You are in the wrong repository for this, as you mentioned this belongs more in core.

./Klaas
