### ISSUE TITLE
Looks good, @yongFans 👍

### ISSUE THREAD

**Issue by yongFans** [home-assistant/brands#4216]
Looks good, @yongFans 👍 

However, I could not find the public GitHub repository that provides this integration. Could you point me to it?

Thanks 👍 

../Frenck

_Originally posted by @frenck in https://github.com/home-assistant/brands/pull/4202#pullrequestreview-1336471818_

**Comment by yongFans** [comment]
@frenck hi ,frenck This is my public github repository  https://github.com/yongFans/brands/tree/master/core_brands/sunricher
thanks!

**Comment by frenck** [comment]
OK, not sure why you created an issue?

I also see you closed your PR. So, I guess you don't want to add it anymore for some reason?

Closing this issue, as it seems to created incorrectly.

../Frenck
