### ISSUE TITLE
MCP23017 I/O Expander is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#427]
## The problem

The MCP23017 I/O Expander integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/mcp23017/icon.png`
- `src/mcp23017/icon@2x.png`
- `src/mcp23017/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @jardiamj! Mind taking a look at this issue as it is with an integration (mcp23017) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/mcp23017/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by LiJu09** [comment]
If are [existing images](https://github.com/home-assistant/brands/tree/master/core_integrations/mcp23017) enough, this issue can be closed.

**Comment by jpcornil-git** [comment]
Issue can be closed I guess
Brands for mcp23017 were available from #2092 (as a core integration) and are now available again from #3217 (as a custom integration)
