### ISSUE TITLE
Météo-France is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#434]
## The problem

The Météo-France integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/meteo_france/logo.png`
- `src/meteo_france/icon@2x.png`
- `src/meteo_france/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @victorcerutti, @oncleben31, @Quentame! Mind taking a look at this issue as it is with an integration (meteo_france) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/meteo_france/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by Quentame** [comment]
@frenck #1016 is adding icons not logos.

Should we re-open this and cross-out the missing icon ?

**Comment by frenck** [comment]
I've looked into it quickly and could not find actually logos (which I guess it the same @cogneato concluded. I'm sure he would have added it if it was available).

![image](https://user-images.githubusercontent.com/195327/78532642-e3ba2780-77e7-11ea-8c20-7e0f28d21ed2.png)

Furthermore, looking at their website, their are using the icons as their logo.

**Comment by Quentame** [comment]
Indeed, I thought of this logo : http://www.legorafi.fr/wp-content/uploads/2012/09/MeteoFrance.png

But it seems it's not used anymore from 2016 : http://i1.wp.com/logonews.fr/wp-content/uploads/2016/02/00_logonews_meteofrance.jpg

My bad, not updated about logos news :grimacing:

**Comment by oncleben31** [comment]
I've made some search. I only find the icon used as logo. The one you have find is old and not used anymore.
