### ISSUE TITLE
Make offline-usage possible

### ISSUE THREAD

**Issue by FibreFoX** [home-assistant/brands#4439]
## The problem

Right now all brand images are always referenced from "https://brands.home-assistant.io/", This is a problem for instances that are used for internal purposes, which are offline or have no direct access to the internet. Even tho "it is the browser" who resolves the image URL (with proper usage of privacy-related html-tags used), this leaves an unwanted request "to the internet".

Please make it possible to "download" or "import" the images of this repository into a local installation of HomeAssistant.

## Additional information
Not sure if this scratches at GDPR legal stuff, but I miss the ability to revoke my consent to have the images being used from the internet source.
When having an offline version import, this might even make it possible for custom logos/images while developing / for internal integrations instead of having them required being made public via pull-requests.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by FibreFoX** [comment]
You should re-evaluate the way your approach. This can be a GDPR issue, and forcing usage of external systems is not "nice" when using GitHub.

**Comment by FibreFoX** [comment]
This is the same argument for google font inclusion violating GDPR rules. If I set up a HA instance, and someone else uses that (web)service, and the browser then sends requests to brands.home-assistant.io, these HTTP-requests send the IP address to a different server.

This does not have to be for tracking scripts only, but includes all external resources.

**Comment by frenck** [comment]
Sorry, you are wrong. If that were true, every request web request would be in direct violation of GDPR.

GDPR is about collecting and processing user data, Google Fonts violates GDPR by collecting and sharing personal information with third-party services without user consent. This is known and documented.

In this case, we don't collect or store any personal data, as a matter of fact, we are not interested in it at all.

You are free not to use, or block this service if you feel uncomfortable using it.

../Frenck

**Comment by FibreFoX** [comment]
Yes, every web request, that was not approved before, can violate the GDPR.

The IP address is considered as personal data, thats especially listed here: https://commission.europa.eu/law/law-topic/data-protection/reform/what-personal-data_en

Processing of the IP address (e.g. in webserver access logs) are viewed as "data processing": https://commission.europa.eu/law/law-topic/data-protection/reform/what-constitutes-data-processing_en

It is not related to "analytics". When my own instance is running somewhere, each request to brands.home-assistant.io is considered "third party", I can not turn off (aka revoking the consent). Thats why I see this as a bug.

**Comment by frenck** [comment]
> The IP address is considered as personal data, thats especially listed here:

Again, we don't store personal information or any data for that matter as per above, nor do we have any interest in such data. You seem to skip over that sentence.

../Frenck
