### ISSUE TITLE
Wrong "dark" version for the automatic logo generated

### ISSUE THREAD

**Issue by fredck** [home-assistant/brands#4471]
## The problem

It seems that an " auto generated logo" image is created for custom integrations that don't have a logo, out of the "icon" image.

To exemplify the issue, let's take the "Lightener" integration:

 * The icon image: https://brands.home-assistant.io/lightener/dark_icon.png
 * The logo image: https://brands.home-assistant.io/lightener/dark_logo.png

Here we have the images for comparison:

Icon:
![](https://brands.home-assistant.io/lightener/dark_icon.png)

Logo:
![](https://brands.home-assistant.io/lightener/dark_logo.png)

Notice that the "dark" logo image doesn't have the yellow border around the bulb. It's in fact a copy of the normal icon image:
https://brands.home-assistant.io/lightener/icon.png

## Additional information

I can't say that for sure but maybe this happened because the Lightener integration icons have been loaded in two different PRs, being the dark one added later (#4255, #4387).

As a result, we can see the difference in the new UI for integrations, which feels like a buggy:

<img width="302" alt="image" src="https://github.com/home-assistant/brands/assets/630060/6f75c097-8ce1-4213-8f87-938615fcb184">

<img width="305" alt="image" src="https://github.com/home-assistant/brands/assets/630060/32e6a6b4-500e-47b8-a7b2-b0551c98ab51">

**Comment by frenck** [comment]
We don't generate images. 

If an image isn't correct, feel free to open up a PR to adjust it.

../Frenck

**Comment by fredck** [comment]
> We don't generate images.

What I meant to say is that somehow a dark version of the logo is being provided for an integration that doesn't have a dark logo. For example:

 * Integration files: https://github.com/home-assistant/brands/tree/master/custom_integrations/lightener
 * Provided dark logo: https://brands.home-assistant.io/lightener/dark_logo.png

The above seems to be automatically generated out of the plain icon, not the dark icon.

I could provided logo images for my integration and solve "my" problem but this would not solve "the" problem.

You may reconsider reopening this issue. Thanks ;)

**Comment by fredck** [comment]
> We don't generate images.

Ok... I believe it's just semantics... I've used the wrong words. But from the README:

"If a domain is missing the logo.png file, the icon.png is served instead (if available)."

"If a image optimised for dark themes (image is prefixed with 'dark_') is missing, it's non-prefixed match will be served instead (if available)."

As a result (reported case):

```
dark_logo.png -> logo.png -> icon.png
```

Preferably it should go like this (in my case, it would stop at `dark_icon.png`):

```
dark_logo.png -> dark_icon.png -> logo.png -> icon.png
```
