### ISSUE TITLE
no generated link for dark icon/logo

### ISSUE THREAD

**Issue by Ludy87** [home-assistant/brands#4504]
## The problem

After the merge https://github.com/home-assistant/brands/pull/4492 the link was only created for the light icon/logo, the generated link for the dark icon/logo is missing - as with other integrations .

https://brands.home-assistant.io/ipv64/dark_logo.png
https://brands.home-assistant.io/ipv64/dark_icon.png

For other integrations, it worked without storing `dark_*.png`

## Additional information

Thanks in advance

**Comment by frenck** [comment]
This is hard cached, the caches of our CloudFlare endpoint are flushed every main release of Home Assistant (first Wednesday of the month), or sooner if the caches expire naturally.

../Frenck

**Comment by Ludy87** [comment]
Thank you for your quick information, I've already made up my mind that I did something wrong.
