### ISSUE TITLE
National Weather Service (NWS) is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#493]
## The problem

The National Weather Service (NWS) integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/nws/icon.png`
- `src/nws/icon@2x.png`
- `src/nws/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @MatthewFlamm! Mind taking a look at this issue as it is with an integration (nws) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/nws/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by MatthewFlamm** [comment]
I'm still under the impression that permission is needed to use the logo according to:

https://www.weather.gov/logorequest

Please advise on how to proceed.

**Comment by frenck** [comment]
We already use them for ages... we are just moving them to this repository.

**Comment by MatthewFlamm** [comment]
I had the same comment when you added the icon originally.

I obviously cannot stop you from moving them, and you have a different viewpoint on this issue.  So if you are okay with the usage, I would request that you move it.  I will not move them without permission granted.
