### ISSUE TITLE
PCAL9535A I/O Expander is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#528]
## The problem

The PCAL9535A I/O Expander integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/pcal9535a/icon.png`
- `src/pcal9535a/icon@2x.png`
- `src/pcal9535a/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @Shulyaka! Mind taking a look at this issue as it is with an integration (pcal9535a) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/pcal9535a/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by Shulyaka** [comment]
Hi! Do you want me to submit the NXP logo or something different?
Do we have some kind of 'GPIO' icon, if that would be more appropriate?

**Comment by mrand** [comment]
I feel pretty strongly that it shouldn't be NXP logo because this is a generic part that other vendors make as well.  Further discussion in #1902.

**Comment by frenck** [comment]
Closing as the integration is being removed.
