### ISSUE TITLE
Plugwise Anna is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#537]
## The problem

The Plugwise Anna integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/plugwise/logo.png`
- `src/plugwise/icon@2x.png`
- `src/plugwise/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @laetificat, @CoMPaTech, @bouwew! Mind taking a look at this issue as it is with an integration (plugwise) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/plugwise/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by CoMPaTech** [comment]
Hi @frenck we'll work on getting those images. Meanwhile we are also getting closer to  a working async of the component - currently undergoing friendly user tests as a custom one. Tnx for the request.

**Comment by CoMPaTech** [comment]
Should be ready to merge
