### ISSUE TITLE
Proliphix is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#542]
## The problem

The Proliphix integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/proliphix/icon.png`
- `src/proliphix/logo.png`
- `src/proliphix/icon@2x.png`
- `src/proliphix/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).
## Updating the documentation repository

Our documentation repository already has a logo for this integration, however, it does not meet the image requirements of this new Brands repository.

If adding images to this repository, please open up a PR to the documentation repository as well, removing the `logo: proliphix.png` line from this file:

<https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/proliphix.markdown>

**Note**: The documentation PR needs to be opened against the `current` branch.
**Note2**: Please leave the actual logo file in the documentation repository. It will be cleaned up differently.

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

**Comment by LanceMcCarthy** [comment]
## Research Result

I was able to track down the branding the company uses for the website assets http://www.proliphix.com/Collateral/Templates/English-US/images/imagep.gif Unfortunately, it is only ~60x60px, so it can't be used for source.

Luckily, I was able to locate a good 311x231 source http://downloads.indigodomo.com/pluginstore/com.berkinet/com.berkinet.ProliphixControl/icon.png.

In case it is removed, here is a copy:

![image](https://user-images.githubusercontent.com/3520532/79967779-47d22200-845d-11ea-8002-59da98d6cf49.png)

**Comment by LanceMcCarthy** [comment]
@frenck I've completed preparing the images (have all 4 ready) but do not see a `current` branch to base mine from. Should I use `master` instead?

**Comment by LanceMcCarthy** [comment]
Also opened documentaiotn update PR https://github.com/home-assistant/home-assistant.io/pull/13131
