### ISSUE TITLE
PTVSD - Python Tools for Visual Studio Debug Server is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#548]
## The problem

The PTVSD - Python Tools for Visual Studio Debug Server integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/ptvsd/logo.png`
- `src/ptvsd/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @swamp-ig! Mind taking a look at this issue as it is with an integration (ptvsd) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/ptvsd/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by LanceMcCarthy** [comment]
## Research result

Reviewing the PTVSD source, there doesn't appear to be a brand-specific icon https://github.com/Microsoft/ptvsd.

Double checking the VS Extensions Marketplace, there isn't one there either: https://marketplace.visualstudio.com/search?term=Python%20debugger%20package&target=VSCode&category=All%20categories&sortBy=Relevance 

Are there any objections to using the Visual Studio Code icon? If yes, what about a custom icons with a python icon overlaid on the VSCode icon?

**Comment by frenck** [comment]
I think the vscode branding makes sense here.
