### ISSUE TITLE
Pushetta is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#552]
## The problem

The Pushetta integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/pushetta/logo.png`
- `src/pushetta/icon@2x.png`
- `src/pushetta/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

**Comment by adrianmihalko** [comment]
Maybe it's time to remove this integration?

<img width="467" alt="Screenshot 2020-04-17 at 20 57 51" src="https://user-images.githubusercontent.com/733361/79604319-23d5b000-80ee-11ea-87d4-e511ac04461d.png">

**Comment by frenck** [comment]
Meh... Yeah, that has been done before...
And then they came back online... 🤷 

I will investigate it a bit. Thanks! 👍

**Comment by frenck** [comment]
The integration has been removed: <https://github.com/home-assistant/core/pull/34497>
