### ISSUE TITLE
Spain electricity hourly pricing (PVPC) is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#556]
## The problem

The Spain electricity hourly pricing (PVPC) integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/pvpc_hourly_pricing/icon.png`
- `src/pvpc_hourly_pricing/logo.png`
- `src/pvpc_hourly_pricing/icon@2x.png`
- `src/pvpc_hourly_pricing/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @azogue! Mind taking a look at this issue as it is with an integration (pvpc_hourly_pricing) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/pvpc_hourly_pricing/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by azogue** [comment]
Hi @frenck, what about #56?

The integration had a svg logo, but I removed it in favour of this new `brands`, and did everything...

**Comment by frenck** [comment]
You are totally right! It was missing on my end when generating these issues!

Thanks for pointing that out 👍
