### ISSUE TITLE
Signal Messenger is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#617]
## The problem

The Signal Messenger integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/signal_messenger/logo.png`
- `src/signal_messenger/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @bbernhard! Mind taking a look at this issue as it is with an integration (signal_messenger) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/signal_messenger/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by bbernhard** [comment]
will do, you can assign it to me :)

**Comment by frenck** [comment]
Done! Thanks, @bbernhard! 👍

**Comment by bbernhard** [comment]
Just had a look at this. Unfortunately, there seems to be no official Signal Messenger logo out there, apart from the already added Signal Messenger icon. I've found a few "unofficial" Signal Messenger logos (created by blogs & other websites), but no official brand logos created by the Signal Foundation for that purpose. 

How should we proceed with that? 
According to the documentation it's not necessary to upload the logo again, in case the the logo would be similar to the icon, right? 

@frenck Please let me know in case there's anything else I can do here :)

**Comment by frenck** [comment]
Well, in that case, let's close it up for now!

Thanks for checking it 👍
