### ISSUE TITLE
Telnet is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#694]
## The problem

The Telnet integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/telnet/icon.png`
- `src/telnet/logo.png`
- `src/telnet/icon@2x.png`
- `src/telnet/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

**Comment by Data-Monkey** [comment]
I can't find any telnet logos or icons. Not sure they exist.
Maybe telnet is from a pre-picture era? :)
