### ISSUE TITLE
Thinking Cleaner is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#702]
## The problem

The Thinking Cleaner integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/thinkingcleaner/icon.png`
- `src/thinkingcleaner/icon@2x.png`
- `src/thinkingcleaner/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

**Comment by samrdev** [comment]
They're not selling devices anymore. What to do with the logos?

**Comment by frenck** [comment]
Their icon is still available in the app store?

<https://is4-ssl.mzstatic.com/image/thumb/Purple60/v4/6f/30/f4/6f30f464-ea92-3c63-cdd5-d8df88bd4185/mzl.jtcvjuhn.png/492x0w.png>

**Comment by samrdev** [comment]
Good point 👍
