### ISSUE TITLE
Air Quality is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#71]
## The problem

The Air Quality integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/air_quality/icon.png`
- `src/air_quality/logo.png`
- `src/air_quality/icon@2x.png`
- `src/air_quality/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

**Comment by samrdev** [comment]
Does this refer to the World Air Quality integration as of https://www.home-assistant.io/integrations/waqi/?

**Comment by frenck** [comment]
No this refers to an internal integration that actually should be symlinked to the `_homeassistant` folder.
