### ISSUE TITLE
Vacuum is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#747]
## The problem

The Vacuum integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/vacuum/icon.png`
- `src/vacuum/logo.png`
- `src/vacuum/icon@2x.png`
- `src/vacuum/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

**Comment by samrdev** [comment]
Which one is meant here?

**Comment by frenck** [comment]
This can be symlinked to the _homeassistant folder.
