### ISSUE TITLE
Water Heater is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#771]
## The problem

The Water Heater integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/water_heater/icon.png`
- `src/water_heater/logo.png`
- `src/water_heater/icon@2x.png`
- `src/water_heater/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

**Comment by samrdev** [comment]
Is this to be symlinked to `_homeassistant`?

**Comment by frenck** [comment]
Yes :+1:
