### ISSUE TITLE
LG webOS Smart TV is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#777]
## The problem

The LG webOS Smart TV integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/webostv/icon.png`
- `src/webostv/logo.png`
- `src/webostv/icon@2x.png`
- `src/webostv/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).
## Updating the documentation repository

Our documentation repository already has a logo for this integration, however, it does not meet the image requirements of this new Brands repository.

If adding images to this repository, please open up a PR to the documentation repository as well, removing the `logo: webos.png` line from this file:

<https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/webostv.markdown>

**Note**: The documentation PR needs to be opened against the `current` branch.
**Note2**: Please leave the actual logo file in the documentation repository. It will be cleaned up differently.

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @bendavid! Mind taking a look at this issue as it is with an integration (webostv) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/webostv/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by BCNelson** [comment]
It looks like there is not icon for web os should we just symlink an LG Logo?

**Comment by Shurov** [comment]
> It looks like there is not icon for web os should we just symlink an LG Logo?

actually there is one, e.g. https://en.wikipedia.org/wiki/WebOS

**Comment by BCNelson** [comment]
I'm not sure that that would be the best for a Icon. It would be hard to make square and when displayed small would be hard to read due to the thin lines. That seems to me to be much more of a logo then an icon.

**Comment by Shurov** [comment]
> That seems to me to be much more of a logo then an icon.

you're right. I've mixed an icon with a logo. Maybe, we could split it in 2 words and place them in 2 lines, so that it'd form a square. Like
`web
  OS`

**Comment by BCNelson** [comment]
I'm not sure that we should be creating our own logos
