### ISSUE TITLE
World Tides is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#784]
## The problem

The World Tides integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/worldtidesinfo/logo.png`
- `src/worldtidesinfo/icon@2x.png`
- `src/worldtidesinfo/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

**Comment by samrdev** [comment]
I couldn't find any applicable icons or logos bigger than 256px. We could use one of the icons in the app stores, but they all have a label saying "2020" on them. Should we contact the developer?

**Comment by frenck** [comment]
Skip it for now, we can always decide later.
