### ISSUE TITLE
World Wide Lightning Location Network (WWLLN) is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#789]
## The problem

The World Wide Lightning Location Network (WWLLN) integration has missing brand images.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/wwlln/icon.png`
- `src/wwlln/icon@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @bachya! Mind taking a look at this issue as it is with an integration (wwlln) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/wwlln/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by rpitera** [comment]
I don't think the WWLLN has any branding.  Even their Twitter presence uses a stock clip art lightning bolt for a user image.

**Comment by BudBundi** [comment]
WWLLN is removed from HA

**Comment by frenck** [comment]
True, closing this one.
