### ISSUE TITLE
Yamaha Network Receivers is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#796]
## The problem

The Yamaha Network Receivers integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/yamaha/icon.png`
- `src/yamaha/logo.png`
- `src/yamaha/icon@2x.png`
- `src/yamaha/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).
## Updating the documentation repository

Our documentation repository already has a logo for this integration, however, it does not meet the image requirements of this new Brands repository.

If adding images to this repository, please open up a PR to the documentation repository as well, removing the `logo: yamaha.png` line from this file:

<https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/yamaha.markdown>

**Note**: The documentation PR needs to be opened against the `current` branch.
**Note2**: Please leave the actual logo file in the documentation repository. It will be cleaned up differently.

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

**Comment by tomlut** [comment]
I've made some logos for this but can't find the folder to upload them to. Can I create it in the src folder?

**Comment by frenck** [comment]
Yes, if the folder is missing, it has to be created (there is no such thing as empty folders in git).

**Comment by tomlut** [comment]
Does not appear I have the required permissions:

```
Uploads are disabled.
File uploads require push access to this repository.
```

**Comment by frenck** [comment]
@tomlut You need to fork the repository, create a feature branch, commit onto that and open up a PR against this repository.

**Comment by samrdev** [comment]
Maybe we can link the yamaha and yamaha_musiccast logos between the folders without touching the icons?

**Comment by frenck** [comment]
Please keep the symlinks on the main integration level.
