### ISSUE TITLE
Yeelight Sunflower is missing brand images

### ISSUE THREAD

**Issue by frenck** [home-assistant/brands#801]
## The problem

The Yeelight Sunflower integration does not have brand images in
this repository.

We recently started this Brands repository, to create a centralized storage of all brand-related images. These images are used on our website and the Home Assistant frontend.

The following images are missing and would ideally be added:

- `src/yeelightsunflower/icon.png`
- `src/yeelightsunflower/logo.png`
- `src/yeelightsunflower/icon@2x.png`
- `src/yeelightsunflower/logo@2x.png`

For image specifications and requirements, please see [README.md](https://github.com/home-assistant/brands/blob/master/README.md).
## Updating the documentation repository

Our documentation repository already has a logo for this integration, however, it does not meet the image requirements of this new Brands repository.

If adding images to this repository, please open up a PR to the documentation repository as well, removing the `logo: yeelight.png` line from this file:

<https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/yeelightsunflower.markdown>

**Note**: The documentation PR needs to be opened against the `current` branch.
**Note2**: Please leave the actual logo file in the documentation repository. It will be cleaned up differently.

## Additional information

For more information about this repository, read the [README.md](https://github.com/home-assistant/brands/blob/master/README.md) file of this repository. It contains information on how this repository works, and image specification and requirements.

## Codeowner mention

Hi there, @lindsaymarkward! Mind taking a look at this issue as it is with an integration (yeelightsunflower) you are listed as a [codeowner](https://github.com/home-assistant/core/blob/dev/homeassistant/components/yeelightsunflower/manifest.json) for? Thanks!

Resolving this issue is not limited to codeowners! If you want to help us out, feel free to resolve this issue! Thanks already!

**Comment by lindsaymarkward** [comment]
This brand doesn't exist, so there are no brand images.
Yeelight Sunflower was like a beta product that didn't go anywhere (except to my house).
If you go to the site, it still says "preorder", like it did 5 years ago.
https://www.yeelight.com/en_US/product/yeelight-sunflower

**Comment by deadman96385** [comment]
It should either be changed to just xiaomi or on the brands side symlink to the xiaomi one.

**Comment by lindsaymarkward** [comment]
@deadman96385 - why?  What's it got to do with Xiaomi at all?
It's essentially a dead/non-existent 'brand'. 
We need to have a way to handle 'brands' that don't exist or don't have brand images.

**Comment by deadman96385** [comment]
Sorry about that I had xiaomi on the mind, I meant to say yeelight. Atleast in this case this mis-labeled brand could be changed to yeelight or if not possible have it use the yeelight pictures.

**Comment by lindsaymarkward** [comment]
That site says:
> Sorry, this item is no longer available!

I think it's misleading to brand it with Yeelight because some people might then be interested in this for their Yeelights, when they're an almost unrelated product. When I submitted the platform, I had people trying to get me to combine it with the existing Yeelight platform and I had to convince them they were totally different.

**Comment by juaigl** [comment]
> 
> 
> This brand doesn't exist, so there are no brand images.
> Yeelight Sunflower was like a beta product that didn't go anywhere (except to my house).
> If you go to the site, it still says "preorder", like it did 5 years ago.
> https://www.yeelight.com/en_US/product/yeelight-sunflower

The page you probide have an icon on the header. How about that?
https://www.yeelight.com/favicons/favicon-196x196.png
![](https://www.yeelight.com/favicons/favicon-196x196.png)

**Comment by lindsaymarkward** [comment]
Sure, looks good. 
If you need an image; that's the one I recognise from when their app worked.

**Comment by frenck** [comment]
Guys... we are trying to store brands.... the brand is Yeelight and thus should be symlinked to the Yeelight folder.
