### ISSUE TITLE
Update icon for cast

### ISSUE THREAD

**Issue by balloob** [home-assistant/brands#968]
## The problem

The current icon looks too much like the MDI icon, which makes it weird in the overview:

![image](https://user-images.githubusercontent.com/1444314/78420356-2078f980-7603-11ea-91cf-8fba259698f8.png)

Found this updated icon that they use on their website: https://www.google.com/chromecast/built-in/static/images/tv/apps.svg

(side note, it looks like it's called Chromecast again, not Google Cast. We should update our name?)

**Comment by cogneato** [comment]
@balloob Nice find for the icon and I agree about the current one. In regard to the name change, should I go with this for logo?
![image](https://user-images.githubusercontent.com/2456810/78420668-5d96b900-760e-11ea-81d0-c3e49da1611b.png)

**Comment by balloob** [comment]
Yeah that's a good one. Wonder if we should get a colored chrome logo?
